package wikiparse

import (
	"reflect"
	"testing"
)

func TestLinkSearch(t *testing.T) {
	t.Parallel()
	exp := []string{
		"Aplysina archeri",
		"Robert Edmund Grant",
		"Robert Bentley Todd",
		"Calcarea",
		"Hexactinellida",
		"Demospongiae",
		"Homoscleromorpha",
		"animal",
		"phylum",
		"mesohyl",
		"Cell (biology)",
		"nervous system",
		"digestive system",
		"circulatory system",
		"osculum",
		"Sessility (zoology)",
		"bacteria",
		"photosynthesis",
		"endosymbiont",
		"carnivore",
		"crustacean",
		"sexual reproduction",
		"sperm",
		"ovum",
		"larva",
		"gemmule",
		"endoskeleton",
		"Biomineralization",
		"sponge spicule",
		"spongin",
		"Demosponge",
		"silica",
		"calcium carbonate",
		"exoskeleton",
		"Calcareous sponge",
		"glass sponge",
		"scaffolding",
		"Archaeocyathid",
		"unicellular",
		"choanoflagellate",
		"monophyletic",
		"Eumetazoa",
		"Homoscleromorpha",
		"Ctenophora",
		"phylum",
		"Sessility (zoology)",
		"metazoa",
		"choanocyte",
		"cnidaria",
		"ctenophore",
		"basal lamina",
		"Cnidarian",
		"ctenophore",
		"Homoscleromorpha",
		"mesohyl",
		"collagen",
		"choanocyte",
		"flagellum",
		"wikt:ostium",
		"porocytes",
		"Pinacocyte",
		"Lophocyte",
		"amoeba",
		"Collencyte",
		"Rhabdiferous",
		"polysaccharide",
		"Oocyte",
		"spermatocyte",
		"Sclerocyte",
		"sponge spicule",
		"skeleton",
		"demosponge",
		"spongocyte",
		"polymer",
		"spongin",
		"Myocyte",
		"immune system",
		"Archaeocytes",
		"amoebocytes",
		"amoeba",
		"totipotent",
		"Glass sponge",
		"silica",
		"scaffolding",
		"Spider web",
		"syncytium",
		"Cell membrane",
		"cell nucleus",
		"cytoplasm",
		"organelle",
		"cytoplasm",
		"sclerocyte",
		"chimney",
		"osculum",
		"pinacocyte",
		"choanocyte",
		"epithelia",
		"oxygen",
		"syconoid",
		"pleat",
		"glass sponge",
		"Leuconia",
		"osculum",
		"calcium carbonate",
		"Pinacocyte",
		"Choanocyte",
		"Archeocyte",
		"mesohyl",
		"Calcium carbonate",
		"skeleton",
		"biomineralization",
		"endoskeleton",
		"sponge spicule",
		"spongin",
		"silica",
		"calcium carbonate",
		"sclerocyte",
		"exoskeleton",
		"sclerosponge",
		"choanocyte",
		"pinacocyte",
		"Homoscleromorpha",
		"Demospongiae",
		"Class (biology)",
		"skeleton",
		"Sponge spicule",
		"Spongin",
		"Calcarea",
		"Calcite",
		"Glass sponge",
		"syncytia",
		"Silica",
		"Demosponge",
		"aragonite",
		"Homoscleromorpha",
		"File:Spongia officinalis.jpg",
		"Spongia officinalis",
		"Sessility (zoology)",
		"amoeba (genus)",
		"pinacocyte",
		"osculum",
		"wikt:ostium",
		"circulatory",
		"respiratory",
		"digestion",
		"excretory",
		"filter feeding",
		"wikt:ostium",
		"pinacocyte",
		"phagocytosis",
		"archaeocyte",
		"choanocyte",
		"Vesicle (biology)",
		"glass sponge",
		"dynein",
		"microtubule",
		"syncytium",
		"diffusion",
		"carbon dioxide",
		"ammonia",
		"crustacea",
		"family (biology)",
		"Cladorhizidae",
		"Guitarridae",
		"Esperiopsidae",
		"sponge spicule",
		"Mediterranean",
		"filter feeding",
		"venom",
		"choanocyte",
		"genus",
		"Chondrocladia",
		"green algae",
		"endosymbiont",
		"archaeocyte",
		"photosynthesis",
		"cyanobacteria",
		"dinoflagellate",
		"University of Stuttgart",
		"spicule",
		"silica",
		"mesohyl",
		"hydrothermal vent",
		"Methanotrophic",
		"immune system",
		"Medical grafting",
		"File:Spongilla lacustris.jpg",
		"Spongilla lacustris",
		"asexual reproduction",
		"budding",
		"gemmule",
		"pinacocyte",
		"choanocyte",
		"mesohyl",
		"collencyte",
		"mesohyl",
		"archeocyte",
		"Spongocyte",
		"spongin",
		"spicule",
		"archeocyte",
		"salinity",
		"pinacocyte",
		"hermaphrodite",
		"gonad",
		"choanocyte",
		"mesohyl",
		"cyst",
		"archeocyte",
		"yolk",
		"osculum",
		"ameboid",
		"flagella",
		"cilia",
		"Glass sponge",
		"ovoid",
		"cilia",
		"syncitium",
		"choanosyncytia",
		"temperate",
		"Tropics",
		"demosponge",
		"neuron",
		"nervous tissue",
		"pinacocyte",
		"osculum",
		"Siamese twins",
		"neurotransmitter",
		"glass sponge",
		"syncytium",
		"flagella",
		"Myocyte",
		"gene",
		"synapse",
		"File:Euplectella aspergillum.jpg",
		"Euplectella aspergillum",
		"deep ocean",
		"glass sponge",
		"California",
		"Glass sponge",
		"Demosponge",
		"Calcarea",
		"Class (biology)",
		"Calcarea",
		"Glass sponge",
		"sediment",
		"Demosponge",
		"photosynthesis",
		"endosymbiont",
		"oxygen",
		"Great Barrier Reef",
		"File:BoredEncrustedShell.JPG",
		"Entobia",
		"Mercenaria mercenaria",
		"North Carolina",
		"File:Entobia Modern.jpg",
		"spicule",
		"echinoderm",
		"bryozoa",
		"sea squirt",
		"ageliferin",
		"Caribbean",
		"Tedania",
		"Glass sponge",
		"Neuroptera",
		"Sisyridae",
		"Ross Piper",
		"Greenwood Publishing Group",
		"Chondrilla nucula",
		"polyp",
		"Clionaidae",
		"mollusk",
		"Aplysina",
		"Aplysina red band syndrome",
		"necrosis",
		"Contagious disease",
		"cyanobacterium",
		"Lissodendoryx",
		"seagrass",
		"starfish",
		"Shrimp",
		"Synalpheus",
		"crustacea",
		"loggerhead sponge",
		"Cretaceous",
		"Archaeocyathid",
		"cholestane",
		"cholesterol",
		"demosponge",
		"eumetazoa",
		"cnidaria",
		"bilateria",
		"choanoflagellate",
		"biochemistry",
		"gene",
		"choanoflagellate",
		"cholestane",
		"Marinoan glaciation",
		"molecular clock",
		"biomarker",
		"Cambrian explosion",
		"Silica",
		"spicule",
		"fossil",
		"Ediacaran",
		"Doushantuo Formation",
		"spicule",
		"pinacocyte",
		"porocyte",
		"archeocyte",
		"sclerocyte",
		"glass sponge",
		"Calcium carbonate",
		"Calcarea",
		"Cambrian",
		"Chengjiang fauna",
		"Eocene",
		"demosponges",
		"Archaeocyathid",
		"File:Cronoflagelado2.jpg",
		"Fungi",
		"Choanoflagellate",
		"Metazoa",
		"Glass sponge",
		"Demosponge",
		"Calcarea",
		"Eumetazoa",
		"Ctenophora",
		"Placozoa",
		"Cnidaria",
		"Calcarea",
		"Plant",
		"Fungi",
		"Metazoa",
		"demosponge",
		"Calcarea",
		"Homoscleromorpha",
		"Eumetazoa",
		"Cnidaria",
		"metazoa",
		"Homoscleromorpha",
		"monophyletic",
		"metazoa",
		"choanoflagellate",
		"choanocytes",
		"Eumetazoa",
		"ribosome",
		"DNA",
		"glass sponge",
		"Calcarea",
		"calcium carbonate",
		"spicule",
		"RNA",
		"Homoscleromorpha",
		"cell nucleus",
		"DNA",
		"Ctenophora",
		"Homoscleromorpha",
		"chancelloriidae",
		"Cambrian",
		"sperm",
		"collagen",
		"spongin",
		"File:Bathocyroe fosteri.jpg",
		"ctenophora",
		"ctenophora",
		"ctenophora",
		"Placozoa",
		"cnidarian",
		"Archaeocyathid",
		"Cambrian",
		"cnidaria",
		"algae",
		"foraminifera",
		"phylum",
		"Kingdom (biology)",
		"Halkieriid",
		"aragonite",
		"spongin",
		"collagen",
		"protein",
		"demosponge",
		"Darwinella",
		"halkieriid",
		"bilaterian",
		"slug",
		"chain mail",
		"dilemma",
		"File:Biological classification L Pengo.svg",
		"Linnean taxonomy",
		"Linnaeus",
		"Vermes in the 10th edition of Systema Naturae#Zoophyta",
		"Vermes",
		"Spongia",
		"Algae",
		"Parazoa",
		"Eumetazoa",
		"Kingdom (biology)",
		"Animalia",
		"phylum",
		"Class (biology)",
		"skeleton",
		"Hexactinellida",
		"spicule",
		"syncytia",
		"Cell membrane",
		"Calcarea",
		"calcite",
		"calcium carbonate",
		"Demospongiae",
		"spongin",
		"aragonite",
		"Archeocyatha",
		"Cambrian",
		"Sclerospongiae",
		"Oxford University Press",
		"tool",
		"bottlenose dolphins",
		"Shark Bay",
		"rostrum (anatomy)",
		"sea floor",
		"Proceedings of the National Academy of Sciences",
		"National Geographic Society",
		"File:Sponges.JPG",
		"Kalymnos",
		"Greece",
		"calcium carbonate",
		"silica",
		"spicule",
		"genus",
		"Hippospongia",
		"Spongia",
		"ceramic glaze",
		"contraceptive",
		"sponge diving",
		"sponge (tool)",
		"breast implant",
		"contraceptive sponge",
		"cellulose",
		"polyurethane",
		"silicone",
		"luffa",
		"gourd",
		"Cucurbitaceae",
		"medicine",
		"symbiosis",
		"virus",
		"bacteria",
		"tumor",
		"oxylipin",
		"Sponge reef",
		"Sponge Reef Project",
		"Adobe Flash",
		"Tarpon Springs, Florida",
		"Category:Poriferans",
		"ar:إسفنجيات",
		"az:Süngərlər",
		"ba:Болоттар",
		"be:Губкі",
		"be-x-old:Губкі",
		"bg:Водни гъби",
		"bs:Porifera (spužve)",
		"br:Spoue",
		"ca:Porífer",
		"cs:Houbovci",
		"cy:Sbwng",
		"da:Svampedyr",
		"de:Schwämme",
		"nv:Táłtłʼááh yilcháazhii",
		"et:Käsnad",
		"el:Σπόγγος",
		"es:Porifera",
		"eo:Spongulo",
		"eu:Belaki",
		"fa:اسفنج دریایی",
		"fr:Porifera",
		"gv:Porifera",
		"gl:Poríferos",
		"ko:해면동물",
		"hi:स्पंज",
		"hr:Spužve",
		"io:Sponjo",
		"id:Porifera",
		"is:Svampdýr",
		"it:Porifera",
		"he:ספוגיים",
		"jv:Porifera",
		"kk:Губкалар",
		"ku:Parazoa",
		"la:Porifera",
		"lv:Sūkļi",
		"lb:Schwämm (Déieren)",
		"lt:Pintys",
		"hu:Szivacsok",
		"mk:Сунѓери",
		"my:စပန်းရေမြှုပ်",
		"nl:Sponsdieren",
		"ja:海綿動物",
		"frr:Swaampen (weederdiarten)",
		"no:Svamper",
		"nn:Svampar",
		"oc:Porifera",
		"pl:Gąbki",
		"pt:Porifera",
		"ro:Spongieri",
		"qu:Puqyala",
		"ru:Губки",
		"sq:Sfungjeri",
		"simple:Sponge",
		"sk:Hubky",
		"sl:Spužve",
		"sr:Сунђери",
		"sh:Spužve",
		"fi:Sienieläimet",
		"sv:Svampdjur",
		"ta:பஞ்சுயிரி",
		"te:స్పంజిక",
		"th:ฟองน้ำ",
		"tr:Süngerler",
		"uk:Губки",
		"vi:Bọt biển",
		"diq:Sunger",
		"zh:多孔动物门",
	}
	found := FindLinks(sponge)

	if !reflect.DeepEqual(exp, found) {
		t.Fatalf("Expected %#v\ngot %#v", exp, found)
	}
}
